Feature/structure generator
codibly/generator-ts pull request #14
Opened 2019-06-17 15:10 UTC by lukasz-dobosz-c

2019-06-18 06:53 UTC, piotr-oles requested changes

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-api/index.ts
> +  private name: any;
nie powinien być to string?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-api/templates/api.ts
> +
nie robimy tutaj od razu metod list, get, create, update, remove?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-api/templates/mock.ts
> +
nie robimy tutaj od razu metod list, get, create, update, remove, all?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-api/templates/dto.ts
> +
nie robimy tutaj od razu typów List, Get, Create, Update, Remove?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/index.ts
> +    const questions = await this.fileConfigs
tutaj chyba ten await jest niepotrzebny :)

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/index.ts
> +      questions: {
to nie powinno być czasem question? albo jeśli questions, to to powinna być tablica :)

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/index.ts
> +      .reduce((acc, current) => acc.concat(current.questions), []);
nie prościej byłoby tak?
``` 
.map(({ questions }) => questions)
.filter(questions => !!questions);
```

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/index.ts
> +  private answers: any;
może warto byłoby stworzyć tutaj interfejs dla answers?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/index.ts
> +  private name: any;
to nie powinno być string?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/templates/component.class.tsx
> +class <%= name %>Pure extends React.Component<<%= name %>.Props> {
nie chcemy mieć czase suffixu Dumb zamiast Pure, jako że to nie jest w sumie Pure?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/templates/component.class.tsx
> +  export type Props = OwnProps & StatProps & DispatchProps;
ostatnio myślałem o tym i wydaje mi się że powinniśmy raczej eksportować `OwnProps` jako `Props`, a `Props` jako `ConnectedProps` - wtedy nie ważne czy komponent jest connectowany czy nie, zawsze jego interfejsem jest `Props`, a nie tak jak teraz `Props` jeżeli jest nie connectowany i `OwnProps` jeżeli jest connectowany.
```
export namespace <%= name %> {
  export type StateProps = {};
  export type DispatchProps = {};
  export type Props = {};
  export type ConnectedProps = Props & StateProps & DispatchProps;
}
```

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/templates/component.class.tsx
> +  export type StatProps = {};
literówka :)

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/templates/component.class.tsx
> +
nie chcemy mieć tutaj już funkcji mapujących z typami?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/templates/component.class.tsx
> +      <Wrapper>
zawsze chcemy mieć wrapper?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/templates/component.function.tsx
> +export const <%= name %> = (props: Props) => {
proponuje to otypować jako `FC<Props>` i usunąć `Props` z typowania argumentu - wtedy dodatkowo na komponencie możemy ustawić takie rzeczy jak `displayName` czy `defaultProps`

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-component/templates/component.function.tsx
> +    <Wrapper>
zawsze chcemy mieć wrapper?

2019-06-18 06:53 UTC, piotr-oles commented on generators/structure-module/index.ts
> +  private name: any;
any?

2019-06-18 06:53 UTC, piotr-oles commented on package-lock.json
> +{
używamy yarn-a a nie npm-a :)

2019-06-18 06:53 UTC, piotr-oles commented on src/fsModules.ts
> +  return getDirectories("./src");
src? widziałem gdzieś że ustawiałeś rootDir więc nie wiem czy to nie powinno być tutaj jakoś uwzględniane

2019-06-18 06:53 UTC, piotr-oles commented on src/fsModules.ts
> +function fsModules() {
może getModulesDirectories?

2019-06-18 06:53 UTC, piotr-oles commented on src/fsModules.ts
> +  const modules = await fsModules();
tam wszędzie używasz metod Sync więc nie musisz tutaj robić await :)

2019-06-18 06:53 UTC, piotr-oles commented on src/fsModules.ts
> +const isDirectory = ({ path }: any) => lstatSync(path).isDirectory();
any?

2019-06-18 06:53 UTC, piotr-oles commented on src/fsModules.ts
> +    .map((dir: any) => ({ name: dir.name, value: dir.name }))
any?

2019-06-18 07:36 UTC, lukasz-dobosz-c commented on generators/structure-component/templates/component.class.tsx
> +      <Wrapper>
może nie zawsze, ale zostawił bym to w templacie, bo w wiekszosci przypadków robimy diva na pierwszym poziomie i przynajmniej nie bedziemy musieli wymyslac nazwy, a jak bedziemy chcieli mieec coś innego niz diva to można zmienic w styled, chyba, ze chodzi o samą nazwę Wrapper?

2019-06-18 07:40 UTC, piotr-oles commented on generators/structure-component/templates/component.class.tsx
> +      <Wrapper>
no właśnie ja używam `<Wrapper/>` w jakiś 10% przypadków - najczęściej nie robię dodatkowego div-a tylko ewentualnie styluje element który tam powinien być, np. `<List />`. Dlatego wydaje mi się że dodanie tutaj Wrapper-a jest troszkę "nachalne" :)

2019-06-18 08:19 UTC, lukasz-dobosz-c commented on generators/structure-api/templates/api.ts
> +
robimy!

2019-06-18 08:22 UTC, lukasz-dobosz-c commented on generators/structure-api/templates/dto.ts
> +
robimy

2019-06-18 09:49 UTC, lukasz-dobosz-c commented on generators/structure-component/index.ts
> +    const questions = await this.fileConfigs
zgadza się

2019-06-18 09:55 UTC, lukasz-dobosz-c commented on generators/structure-component/index.ts
> +      .reduce((acc, current) => acc.concat(current.questions), []);
no raczej, nie wiem co mi przysżło do głowy

2019-06-21 10:09 UTC, piotr-oles requested changes

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-api/templates/api.ts
> +  export function list(): Promise<<%= name %>Dto.ListElement[]> {
chyba chcemy żeby API od razu mapowało więc tutaj powinny być zwracane raczej modele a nie dto :)

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-api/templates/api.ts
> +  export function get(entityId: <%= name %>Dto.Get['id']): Promise<<%= name %>Dto.Get> {
zmieniłbym nazwę argumentu z entityId na `<%= nameCamelCase %>Id`

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-api/templates/dto.ts
> +  type Identifier = { id: string };
co myślisz o zmianie nazwy typu na `Id`? :)

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-api/templates/dto.ts
> +  export interface ListMeta { pagination: { index: number, size: number, count: number }}
to raczej chcielibyśmy mieć wyciągnięte w jednym miejscu - pominąłbym klucz meta na razie

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-api/templates/dto.ts
> +  export interface List { data: ListElement[], meta: ListMeta }
dlaczego tutaj interfejs a gdzie indziej type?

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-api/templates/mock.ts
> +  export function mockGet(mock: MockAdapter) {
nie chcieliśmy się pozbyć przedrostku mock?

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-component/index.ts
> +  private fileConfig: FileConfig[];
nie powinno być fileConfigs?

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-component/templates/component.class.tsx
> +const mapDispatchToProps = (dispatch: Dispatch): <%= name %>.DispatchProps => ({ });
pewnie będziemy chcieli mieć też AppDispatch (którym będzie tak na prawdę ThunkDispatch z odpowiednimi typami w generyku)

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-component/templates/component.function.tsx
> +  return ( );
może return null?

2019-06-21 10:09 UTC, piotr-oles commented on generators/structure-component/templates/style.styled-components.ts
> +export const Styled = styled.div({
chcemy użwać obiektów czy template-string?

2019-06-21 10:09 UTC, piotr-oles commented on src/const/TaskLabel.ts
> +export const TaskLabel: { [key in Task]: string } = {
nie lepiej byłoby dodać do enum-a `Task` namespace `Task` i mieć to w jednym pliku?
```
export namespace Task {
  const LABELS: {} ...

  export function getLabel(task: Task): string {
    return LABESL[task] || '';
  }
}
```

2019-06-21 11:37 UTC, lukasz-dobosz-c commented on generators/structure-api/templates/dto.ts
> +  type Identifier = { id: string };
może być

2019-06-21 11:38 UTC, lukasz-dobosz-c commented on generators/structure-component/index.ts
> +  private fileConfig: FileConfig[];
powinno

2019-06-21 11:39 UTC, lukasz-dobosz-c commented on generators/structure-api/templates/dto.ts
> +  export interface List { data: ListElement[], meta: ListMeta }
ts-lint `interface-over-type-literal- możemy podyskutować

2019-06-21 11:41 UTC, lukasz-dobosz-c commented on src/const/TaskLabel.ts
> +export const TaskLabel: { [key in Task]: string } = {
dobre, dobre

2019-06-21 12:32 UTC, lukasz-dobosz-c commented on generators/structure-component/templates/style.styled-components.ts
> +export const Styled = styled.div({
temaplate-strg

2019-06-21 14:21 UTC, piotr-oles requested changes

2019-06-21 14:21 UTC, piotr-oles commented on generators/structure-model/templates/model.ts
> +  type Base = Overwrite<<%= name %>Dto.Base, {}>;
tutaj jest zduplikowany typ Base

2019-06-21 15:05 UTC, piotr-oles approved these changes

2019-06-21 15:12 UTC, merged

2019-06-21 15:16 UTC, piotr-oles commented
:tada: This PR is included in version 1.0.1-beta.7 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/generator-codibly-ts)
- [GitHub release](https://github.com/codibly/generator-ts/releases/tag/v1.0.1-beta.7%40beta)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: